# Generated by Django 4.2.19 on 2025-03-31 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('returned', 'Returned'), ('approved', 'Approved')], default='draft', max_length=10)),
                ('reason_for_return', models.TextField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('form_type', models.CharField(max_length=100)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='diploma_pdfs/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('admin_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
